import { createFileRoute } from '@tanstack/react-router';
import { llms } from 'fumadocs-core/source';
import { source } from '@/lib/source';

/**
 * `llms.txt` — a page-tree index (title + one-line description per page) in
 * the format https://llmstxt.org/ describes, generated by fumadocs-core's
 * own `llms()` helper. Verified present in the installed
 * `fumadocs-core@16.11.5` (`fumadocs-core/dist/source/llms.js`) before using
 * it — it only exposes `index()` / `indexNode()`, no full-content `full()`
 * export, hence the hand-rolled `llms-full.txt` in `llms-full[.]txt.ts`.
 *
 * `source` carries the `_i18n` config from `loader({ i18n, ... })` (see
 * `src/lib/source.ts`), so calling `index()` with no `lang` produces both
 * locales' outlines, one after the other, in one file — this is why
 * `sourceForLocale` (built for the single-locale search indices) isn't
 * needed here.
 */
const llmsIndex = llms(source);

export const Route = createFileRoute('/llms.txt')({
  server: {
    handlers: {
      GET: () =>
        new Response(llmsIndex.index(), {
          headers: { 'content-type': 'text/plain; charset=utf-8' },
        }),
    },
  },
});
